version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: marcial
      POSTGRES_PASSWORD: hola123
      PGDATA: /data/postgres
      POSTGRES_DB: ecommerce
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
